disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Writing Site"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "Writing homeworks of TeknolojiAIHL"
